import Footer from '@/components/layout/footer/Footer'
import Header from '@/components/layout/header/Header'
import AuthContext from '@/context/AuthContext'
import '@/styles/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Lord',
  description: 'Generated by create next app',
}

export default function LordLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContext>
          <main className="flex min-h-screen flex-col items-center justify-between"> 
            <Header/>
            {children}
            <Footer/>
          </main>
        </AuthContext>
      </body>
    </html>
  )
}
